export {default as HeroPage} from './Hero'
export {default as About} from './About'
export {default as Contact} from '../Shared/Contact'
export {default as Portfolio} from './Portfolio'
export {default as Resume} from './Resume'
export {default as Service} from './Service'
// export {default as About} from './About'